import assert from 'node:assert/strict';
import { Input } from '../src/core/Input.js';
import { AdaptiveResolution } from '../src/core/AdaptiveResolution.js';
globalThis.window = new EventTarget();
globalThis.document = new EventTarget();
const input = new Input( new EventTarget() );
input.setTouchKey( 'KeyW', true );
assert.equal( input.down( 'KeyW' ), true );
assert.equal( input.hit( 'KeyW' ), true );
input.endFrame();
input.setTouchKey( 'KeyW', true );
assert.equal( input.hit( 'KeyW' ), false );
input.keys.add( 'KeyW' );
input.clearTouch();
assert.equal( input.down( 'KeyW' ), true, 'touch release must not release a physical key' );
input.touchPrimary = true;
input.look.x = 10;
window.dispatchEvent( new Event( 'blur' ) );
assert.equal( input.down( 'KeyW' ), false );
assert.equal( input.touchPrimary, false );
assert.equal( input.consumeLook().x, 0 );
const a = new AdaptiveResolution( { initial: 0.7, max: 0.7 } );
let scale = 0.7;
for ( let i = 0; i < 1200; i++ ) scale = a.update( 1 / 30 ) ?? scale;
assert.equal( scale, 0.5, 'sustained slow frames lower resolution to a bounded floor' );
for ( let i = 0; i < 3600; i++ ) scale = a.update( 1 / 60 ) ?? scale;
assert.equal( scale, 0.7, 'sustained headroom restores resolution without exceeding the preset' );
const b = new AdaptiveResolution( { initial: 0.7, max: 0.7 } );
assert.equal( b.update( 2 ), null, 'background pauses must not lower quality' );
assert.equal( b.update( NaN ), null );
// A 5 FPS scene must still reduce quality instead of being mistaken for a pause.
const slow = new AdaptiveResolution( { initial: 0.7 } );
let slowScale = 0.7;
for ( let i = 0; i < 300; i++ ) slowScale = slow.update( 0.2 ) ?? slowScale;
assert.equal( slowScale, 0.5 );
const { Engine } = await import( '../src/engine/Engine.js' );
let tick;
globalThis.requestAnimationFrame = cb => { tick = cb; return 1; };
const engine = new Engine( null );
let measured;
engine.start( ( dt, elapsed, raw ) => { measured = { dt, raw }; } );
tick( performance.now() + 250 );
assert.equal( measured.dt, 0.1, 'physics still clamps large steps' );
assert.ok( measured.raw >= 0.25, 'frame diagnostics receive the actual elapsed time' );

console.log( 'Mobile input, adaptive resolution, and raw frame timing tests passed' );
